# -*- coding: utf-8 -*-
"""Movierecommend Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TF_rWnpKPU7jewcD804cpandjBK7hE-H

MOVIES RECOMMENDATION PROJECT
"""

import numpy as np
import pandas as pd

data=pd.read_csv('ratings.csv')
data.head()

movies=pd.read_csv('movies.csv')
movies.head(7)

data=data.merge(movies,on='movieId',how='left')
data.head()

average_ratings=pd.DataFrame(data.groupby('title')['rating'].mean())
average_ratings.head()

average_ratings['Total Ratings']=pd.DataFrame(data.groupby('title')['rating'].count())
average_ratings.head()

movie_user=data.pivot_table(index='userId',columns='title',values='rating')
movie_user.head()

correlations=movie_user.corrwith(movie_user['Heat (1995)'])
correlations.head()

recommendation=pd.DataFrame(correlations,columns=['Correlation'])
recommendation.dropna(inplace=True)
recommendation=recommendation.join(average_ratings['Total Ratings'])
recommendation.head()

recc=recommendation[recommendation['Total Ratings']>100].sort_values('Correlation',ascending=False).reset_index()

recc=recc.merge(movies,on='title',how='left')
recc.head(10)